name: mi_promotora
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.7+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter # Add this line

  audioplayer_web: 0.7.1
  audioplayer: 0.8.1
  cached_network_image: ^2.3.2+1
  syncfusion_flutter_charts: ^18.4.43+2
  dio: ^3.0.10
  flutter_launcher_icons: ^0.8.1
  flutter_rounded_progress_bar: ^0.1.2
  flutter_search_bar: ^2.1.0
  font_awesome_flutter: ^8.8.1
  global_configuration: ^1.6.0
  grouped_buttons: ^1.0.4
  http: ^0.12.2
  intl: ^0.17.0-nullsafety.2
  pie_chart: ^4.0.1
  random_color: ^1.0.5
  recase: ^3.0.1
  rxdart: ^0.24.1
  shared_preferences: ^0.5.2
  smart_select: ^4.3.2
  sticky_headers: "^0.1.8"
  string_similarity: ^1.1.0
  url_launcher: ^5.7.10
  webview_flutter: ^1.0.7
  youtube_player_flutter: ^8.0.0
  cupertino_icons: ^1.0.0
  firebase_messaging: ^7.0.3
  flutter_markdown: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/img/IOS.png"
  image_path_android: "assets/img/Android.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/config/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AsapBold
      fonts:
        - asset: assets/fonts/Asap/Asap-Bold.ttf

    - family: AsapBoldltalic
      fonts:
        - asset: assets/fonts/Asap/Asap-BoldItalic.ttf

    - family: AsapItalic
      fonts:
        - asset: assets/fonts/Asap/Asap-Italic.ttf

    - family: AsapMedium
      fonts:
        - asset: assets/fonts/Asap/Asap-Medium.ttf

    - family: AsapMediumItalic
      fonts:
        - asset: assets/fonts/Asap/Asap-MediumItalic.ttf

    - family: AsapRegular
      fonts:
        - asset: assets/fonts/Asap/Asap-Regular.ttf

    - family: AsapSemiBold
      fonts:
        - asset: assets/fonts/Asap/Asap-SemiBold.ttf

    - family: AsapSemiBoldItalic
      fonts:
        - asset: assets/fonts/Asap/Asap-SemiBoldItalic.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
